

module.exports = {
    pdfTitle:'FACT Licence',
    pdtSubtitle:'Your API Terms are Fair, Transparent and Trustworthy. It’s a FACT.',
     abstractText:`The FACT (for FAIR API Commitment to Trust) licence is a customizable Contract that expands upon traditional API Terms of Service (ToS). Its purpose is to promote API usage  and  allow API Users to develop interoperable products, whether they be new APIs or other types of products.

     Using a standardized set of contracts that are widely accepted as safe by the community, the Core API Provider and API Users can reduce transaction costs.  The licence also aims to raise the users’ awareness of key licensing issues that the parties need to address. Furthermore, it helps companies to define a clear, unambiguous and legally-binding framework that encourages the development of products interoperable with their technologies. This can lead tot the creation of high-value products and services in a healthy, trustworthy and safe digital infrastructure ecosystem.
     
     The FACT Contract is drafted neutrally to cover all rights related to API usage including Intellectual Property rights such as patents, copyrights and trade secrets, regardless of their validity. The standard terms of the FACT licence, along with all other specific binding documents, listed in the “API contractual commitments summary”, make up the entire contract.
     `,
    legalAndDisclaimer:`As a result of our research, the FACT licence is distributed under a Creative Commons Attribution 4.0 International Public Contract (CC BY 4.0). This original Contract is a pilot based on the INTILA (Interoperability Information Licence Agreement), and will evolve in response to feedback and usage.
    
    We are not a law firm and do not offer legal services or advice. The Distribution of this Contract does not create a lawyer-client or any other kind of relationship. We provide this Contract and related information on an “as-is” basis, without warranties regarding the Contract, any material licensed under its terms and conditions, or any related information. We disclaim all liability for damages resulting from their use to the fullest extent possible.
    `,
    originOfProjectText:`FACT is a result of APIToS-CC research project  funded by the Critical Digital Infrastructure Grant from the Ford Foundation, Sloan Foundation, Mozilla, Omidyar, and Open Society Foundations. The project aimed to explore the best framework for API terms of Service. As a contract, that can be  automatically read, controlled and enforced between digital infrastructure and applications to improve the trustworthiness and sustainability of digital infrastructures. This Contract is the original version that is both human-readable and easy to automate. The goal is to allow each API provider to auto-generate a specific version of the Contract complemented with its additional terms, and to make the entire set machine-readable` ,
    ourGoals:`Web APIs play a vital role in the development of our digital society, placing increasing responsibilities on API providers. They have the power and responsibility to ensure fair, valuable, and socially ethical use of their APIs, which is essential for the sustainable and ethical growth of their ecosystem.

    We aim  to promote a fair offer and use of API ToS by developing and making available to all users a common agreement that ensures sustainable trust with providers.

    This Contract which we suggest calling FACT (acronym for "FAIR API Commitment to Trust") should allow Core API Providers, in both the private and public sectors, as well as API Users (primarily businesses although end users may directly benefit) to reduce mistrust and ambiguity by relying on a set of commonly accepted contract terms which are considered safe by a large community.

    It should also help companies define a clear, unambiguous and legally consolidated framework that encourages the use of APIs and the development of products or services interoperable with such APIs.
    `,
    mutualCommitment:`This Contract outlines and legally enforces the main commitments voluntarily agreed to by the Core API Providers or by the API Users.

    The contractual relationship between an API provider and an API user can be based on a multitude of heterogeneous contractual documents, which undermines secure collaboration. Although this Contract does not provide one single solution, but a set of good practices (standard terms with different options) and greater transparency by requiring the Core API Provider to bring together all other enforceable documents (such as private contracts, trademark over the name, or privacy rights / data protection rights over information in the contents) into a single "API contractual commitments summary" (see Annex A). The API Core Provider should use the FACT Licence with other agreements (such as the Open Data Licence or any other licence). In this case, the Core API Provider should describe in the Appendix (Annex A) the rights govern what contents together in the individual record or in some other way that clarifies what rights apply. This Contract, i.e. the FACT and the Annexes, constitutes the entire agreement on all matters concerning the API User’s right to use the API and to exploit API Users' Product or API Users' Services. In case of contractual conflicts, the FACT core commitments of the Contract should prevail on any other of these other contractual documents listed in the “API contractual commitment summary” (see Annex A).
    
    This Contract may be sufficient on its own as a minimum set of requirements in a situation where access is open to all, without financial compensation. Used independent permits as described below: access to the API by anyone, grants a free licence for the API specification, allows for free reuse of the data only within the context of using the API  (by either the API Users or their end-users), does not impose limitation on outputs, and requires minimum attributions.
    `,
    definitionList:[`Core API Provider” means the Provider of the API licensed under this Contract.`,
    `“API User” means any individual or legal entity exercising rights under this Contract, API Users irrevocably accept this Contract and all of its terms and conditions by exercising any rights granted by the Contract such as the use of the API, the Development or Exploitation of API Users' Products or Services.`,
    `“API Specification” means the documentation containing the technical description of the API provided by the Core API Provider under this Contract.`,
    `“API Users' Product” means any data set, computer file, computer program, or any electronic hardware device, or any combination of these, which implements the API Specification to communicate with the API, or which creates, writes, reads or displays files in accordance with the API Specification and in a way that would infringe on the licensed Intellectual Property if the API Users did not benefit from the licence grant provided in this Contract under Article 3.2.`,
`“API Users' Services” means services offered by the API Users to third parties, including End Users, using the API Users' Products, but without Distributing the API Users' Products. API Users' Services include providing remote access to third parties to the functionalities of the API Users' Product over a network without enabling such third parties to make or receive copies or units of the API Users' Product).`,
`“End User” means a third-party customer (individual or entity) to which a copy of, or access to, an API Users' Product or a service based thereon is Distributed or otherwise provided for this third-party customer's own purposes and not for sublicence or further distribution to others unless expressly authorised by the Contract.`,
`“Intellectual Property” means any and all intellectual property rights related to the use of the API, including all the following and all rights in, arising out of, or associated therewith: (i) procedures, designs, inventions, and discoveries; (ii) works of authorship, copyrights, and other rights in works of authorship; and (iii) know-how, show-how and trade secrets on a worldwide basis, including all Patents issued or issuable thereon, but excluding all trademarks, trade names, or other forms of corporate or product identification. “Patents” means all classes or types of patents (including, without limitation, originals, divisions, continuations, continuations-in-part, extensions, re-examinations and reissues, as well as any patent-like intellectual property rights protecting inventions such as Utility Patents), and applications for these classes or types of patent rights in all countries of the world that are owned or controlled by the Core API Provider during the term of this Contract.`,
`“Distribute or Distribution” means licensing, distributing, offering for sale, selling, leasing, providing online access to, communicating, exporting, importing or otherwise making available the API Users' Products in any manner to a third party – referred to as the End Users – so that such third party is provided with the API Users' Product.`,
`“Database” means a collection of content (information, images, audiovisual material, and sounds all in the same database, for example) arranged in a systematic or methodical way and individually accessible through the API thanks to the Contract. The use of the Database and the data itself might be governed by specific licences.`,
`“Develop” means to design, develop, make or have made, and/or produce or have produced API Users' Products in accordance with the API Specification`
],
apiAccessAndGrantOfRights:`The API is available for free and accessible as long as the conditions mentioned in article 4 (API Users' Commitments)  are respected. These conditions include the development of third party internal or external applications, the development, and publication of production products that consume the API internally or externally, and the distribution and provision of access to the API to End Users. The following terms describe under what conditions the API is provided, how the API Users are expected to use the API as well as the API Users’ rights and obligations when using the API-content in their own products (API Users' Product) or services (API Users' Services). The goal of this Contract is to grant the API User rights of use, that would otherwise infringe upon the exclusive rights of the Core API Providers. It is not, and should not serve as a commercial service agreement (such Agreement, is covered in Annexe A if applicable).

Subject to all this provisions and in terms of API Users’ compliance, the Core API Provider grants to the API Users an access and a licence on the Core API Provider's Intellectual Property (see duration in Article 10, worldwide, non-exclusive, non-transferable and personal licence)  only for the following purposes: 
`,
continuosAccess:`If the Core API Provider uses an official API Specification document, the Core API providers commits to using the API Specification as the sole source of truth for tracking interoperability changes on the API.

If not, the Core API Provider will provide the API Users with access to the complete Technical Specification via its online site or other reasonable method determined by the Core API Provider from time to time as described in Annex A. The Core API provider to using this source  as the source of truth for development for the tracking interoperability changes on the API`,
modifications:`If and when the Core API Provider makes corrections and modifications to  the API, the Core API Provider will provide  an updated Technical Specification (new version of the Technical Specification), by posting it in the Core API Provider online site or communicating through other means to notify API Users of the adoption of the updated version.

The Core API Provider will notify API Users of any significant change to its API at least three months before implementing them, allowing API Users to update their implementation gradually. Past versions of the API will remain accessible for at least one year from the date of publication of the API Specification change.`,
specificationContract:`The Core API Provider waives and/or agrees not to prevent or assert any right or authority that would prohibit from using the Specification to exercise the licensed Rights. Simply making and using Products or Services authorized by this Section 3.3 will be permitted under this Agreement.`,
purpose:`The Core API Provider retains the right to update and modify the API,  API-content and this Contract in accordance with its Change Policy. If such a policy exists, it outlines the types of  changes that may occur, how they are communicated to Users and the notice period given. This policy is included in the API contractual commitment summary, as described in Annex A).

However, the Core API Provider is dedicated to ensuring that its Change Policy is fair, that any changes are transparent and protect the interests of API Users. Therefore :
`,
technicalModificationsList:[
    `Notify the API Users at least 3 months in advance (or more)  of any change to the API or major version updates to the technical interface;`,
    `Publish all minor versions (adding a number) for all non-breaking changes to the API interface;`,
    `Announce the API Deprecation period at least 3 months in advance (or more) and maintain it for at least 12 months before sunsetting.`
],
contractualModifications:`The Core API Provider commits to documenting all updates to the API ToS and providing direct communication to API Users for any major change at least 3 months in advance.
The Core API provider also commits to justifying and providing notice period of at least 3 months before  revoking of API access, except in cases where  the current use is deemed unlawful where an exceptional and justified explanation will be given, and evocation may be immediate. The Core API Provider will provide  a FAIR  period  of 3 months to the API consumer  to prove that its use was not against API ToS, End User Licence Agreement, or platform policy and regain API access.

The Core API Provider will also respect a minimum 3 months  notice period before making any change to the documents listed on the “API contractual commitments summary” (Annex A) (this includes Service Level Agreement, pricing, Restriction on Data Reuse applications, etc.).

All modifications to this Contract must be properly documented by releasing a new version of these terms. The Core API Provider will keep a record of all API changes in an API Changelog, which will be published, versioned and maintain a history.  In case it is not possible to maintain an API Changelog, the Core API Provider will assign a version number to each new version, set out at the end of the document, and ensure that previous versions remain publicly available.

By continuing to use the API after a change has been executed, API Users confirm their acceptance of the updated terms. However, if API Users do not accept a change, they must discontinue their connection to the API in accordance with the section ”Term and Termination” section below, and will no longer be entitled to use the API
`,
gdprPolicy:`The General Data Protection Regulation (GDPR) sets out detailed requirements for companies and organisations on collecting, storing and managing personal data. It applies to both European organisations that process personal data of individuals in the EU, and organisations outside the EU that target people living in the EU. The Core API Provider ensures it is compliant with the GDPR regulation.

Unless  specifically stated, the Core API Provider does not collect or manage any personal data in the sense of the GDPR. However, i any personal data is accessible via its API, the Core API provider guarantees that the data is compliant with Data protection requirements such as Purpose, Legal basis, Data Category, Data retention, recipients, and data Localization. In such case, the Core API Provider will add a link to its GDPR policy on the API contractual commitment summary (Annex A).`,
dataLicence:`To the fullest extent permitted by applicable law, but not in violation of it the Core API Provider hereby overtly, fully, permanently, irrevocably and unconditionally waives, abandons, and surrenders all of its Copyright and Related Rights, as well as associated claims and causes of action, whether presently known or unknown (including current and future claims and causes of action), in the data provided through its API in all territories worldwide for the maximum duration allowed by applicable law or treaty (including future time extensions), in any current or future medium and for any number of copies, and for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes. The Core API Provider makes this waiver for the benefit of each User API and their Final Users, with the full intention that such waiver shall not be subject to revocation, rescission, cancellation, termination, or any other legal or equitable action to disrupt the peaceful enjoyment of the data.`
};