

module.exports = {
    pdfTitle:'FACT Licence',
    pdtSubtitle:'Your API Terms are Fair, Transparent and Trustworthy. It’s a FACT.',
     abstractText:`The FACT (for FAIR API Commitment to Trust) licence is a customizable Contract that expands upon traditional API Terms of Service (ToS). Its purpose is to promote API usage  and  allow API Users to develop interoperable products, whether they be new APIs or other types of products.

     Using a standardized set of contracts that are widely accepted as safe by the community, the Core API Provider and API Users can reduce transaction costs.  The licence also aims to raise the users’ awareness of key licensing issues that the parties need to address. Furthermore, it helps companies to define a clear, unambiguous and legally-binding framework that encourages the development of products interoperable with their technologies. This can lead tot the creation of high-value products and services in a healthy, trustworthy and safe digital infrastructure ecosystem.
     
     The FACT Contract is drafted neutrally to cover all rights related to API usage including Intellectual Property rights such as patents, copyrights and trade secrets, regardless of their validity. The standard terms of the FACT licence, along with all other specific binding documents, listed in the “API contractual commitments summary”, make up the entire contract.
     `,
    legalAndDisclaimer:`As a result of our research, the FACT licence is distributed under a Creative Commons Attribution 4.0 International Public Contract (CC BY 4.0). This original Contract is a pilot based on the INTILA (Interoperability Information Licence Agreement), and will evolve in response to feedback and usage.
    
    We are not a law firm and do not offer legal services or advice. The Distribution of this Contract does not create a lawyer-client or any other kind of relationship. We provide this Contract and related information on an “as-is” basis, without warranties regarding the Contract, any material licensed under its terms and conditions, or any related information. We disclaim all liability for damages resulting from their use to the fullest extent possible.
    `,
    originOfProjectText:`FACT is a result of APIToS-CC research project  funded by the Critical Digital Infrastructure Grant from the Ford Foundation, Sloan Foundation, Mozilla, Omidyar, and Open Society Foundations. The project aimed to explore the best framework for API terms of Service. As a contract, that can be  automatically read, controlled and enforced between digital infrastructure and applications to improve the trustworthiness and sustainability of digital infrastructures. This Contract is the original version that is both human-readable and easy to automate. The goal is to allow each API provider to auto-generate a specific version of the Contract complemented with its additional terms, and to make the entire set machine-readable` ,
    ourGoals:`Web APIs play a vital role in the development of our digital society, placing increasing responsibilities on API providers. They have the power and responsibility to ensure fair, valuable, and socially ethical use of their APIs, which is essential for the sustainable and ethical growth of their ecosystem.

    We aim  to promote a fair offer and use of API ToS by developing and making available to all users a common agreement that ensures sustainable trust with providers.

    This Contract which we suggest calling FACT (acronym for "FAIR API Commitment to Trust") should allow Core API Providers, in both the private and public sectors, as well as API Users (primarily businesses although end users may directly benefit) to reduce mistrust and ambiguity by relying on a set of commonly accepted contract terms which are considered safe by a large community.

    It should also help companies define a clear, unambiguous and legally consolidated framework that encourages the use of APIs and the development of products or services interoperable with such APIs.
    `,
    mutualCommitment:`This Contract outlines and legally enforces the main commitments voluntarily agreed to by the Core API Providers or by the API Users.

    The contractual relationship between an API provider and an API user can be based on a multitude of heterogeneous contractual documents, which undermines secure collaboration. Although this Contract does not provide one single solution, but a set of good practices (standard terms with different options) and greater transparency by requiring the Core API Provider to bring together all other enforceable documents (such as private contracts, trademark over the name, or privacy rights / data protection rights over information in the contents) into a single "API contractual commitments summary" (see Annex A). The API Core Provider should use the FACT Licence with other agreements (such as the Open Data Licence or any other licence). In this case, the Core API Provider should describe in the Appendix (Annex A) the rights govern what contents together in the individual record or in some other way that clarifies what rights apply. This Contract, i.e. the FACT and the Annexes, constitutes the entire agreement on all matters concerning the API User’s right to use the API and to exploit API Users' Product or API Users' Services. In case of contractual conflicts, the FACT core commitments of the Contract should prevail on any other of these other contractual documents listed in the “API contractual commitment summary” (see Annex A).
    
    This Contract may be sufficient on its own as a minimum set of requirements in a situation where access is open to all, without financial compensation. Used independent permits as described below: access to the API by anyone, grants a free licence for the API specification, allows for free reuse of the data only within the context of using the API  (by either the API Users or their end-users), does not impose limitation on outputs, and requires minimum attributions.
    `
};